name: Frontend Deployment

on:
  push:
    branches: [main]
    paths:
      - "client/**"
      - ".github/workflows/production-deployment.yml"
      - "deploy.sh"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        

      - name: Deploy to DigitalOcean
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "Deploying to DigitalOcean..."
          ssh -o "StrictHostKeyChecking=no" $SSH_USER@$SSH_HOST 'bash -s' < deploy.sh
